/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\ASUS Ultrabook\\Desktop\\Projects\\Steem Inc\\Projects\\steem sdk\\website\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-95f39f58",
    path: "/glossary/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-95f39f58").then(next)
    },
  },
  {
    path: "/glossary/index.html",
    redirect: "/glossary/"
  },
  {
    name: "v-796584f1",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-796584f1").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-72747704",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72747704").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-f678053e",
    path: "/libraries/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f678053e").then(next)
    },
  },
  {
    path: "/libraries/js/index.html",
    redirect: "/libraries/js/"
  },
  {
    name: "v-2827ac13",
    path: "/resources/dev/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2827ac13").then(next)
    },
  },
  {
    path: "/resources/dev/index.html",
    redirect: "/resources/dev/"
  },
  {
    name: "v-66b33129",
    path: "/standards/content/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66b33129").then(next)
    },
  },
  {
    path: "/standards/content/index.html",
    redirect: "/standards/content/"
  },
  {
    name: "v-5c143d7f",
    path: "/standards/culture/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c143d7f").then(next)
    },
  },
  {
    path: "/standards/culture/index.html",
    redirect: "/standards/culture/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]