/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Steem SDK",
  "description": "Steem SDK is a collection of guides on Steem libraries and specifications recommended practices and standards.",
  "base": "/",
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Steem Development Kit",
        "tagline": "Get ready to turn your ideas into the next big DApp on the Steem blockchain.",
        "actionText": "Get Started →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Standards",
            "details": "Explore recommended standards for content creation, practices and common cultures."
          },
          {
            "title": "Libraries",
            "details": "Documentation for official and community maintained Steem software libraries."
          },
          {
            "title": "Resources",
            "details": "Discover official and community maintained resources for developers and witnesses."
          }
        ],
        "footer": "MIT Licensed | Copyright © 2019-present Steem Institute"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-796584f1",
      "path": "/",
      "lastUpdated": "12/23/2019, 3:10:21 PM"
    },
    {
      "title": "Glossary of words",
      "frontmatter": {
        "title": "Glossary of words",
        "meta": [
          {
            "name": "description",
            "content": "Glossary of popular Steem and Steemian jargons, terms slangs like 'minor', 'witness' and '#rewardpoolrape'. Find the definition of 'official' terms too, such as 'Steem Dollars', 'Steem Power' and more."
          },
          {
            "name": "keywords",
            "content": "steem glossary, steem jargons, steem terms definition, steem dictionary"
          }
        ]
      },
      "regularPath": "/glossary/",
      "relativePath": "glossary/README.md",
      "key": "v-95f39f58",
      "path": "/glossary/",
      "headers": [
        {
          "level": 2,
          "title": "Glossary",
          "slug": "glossary"
        },
        {
          "level": 2,
          "title": "People",
          "slug": "people"
        },
        {
          "level": 3,
          "title": "Minor",
          "slug": "minor"
        },
        {
          "level": 3,
          "title": "Whale",
          "slug": "whale"
        },
        {
          "level": 3,
          "title": "Curator",
          "slug": "curator"
        },
        {
          "level": 3,
          "title": "Witnesses",
          "slug": "witnesses"
        },
        {
          "level": 3,
          "title": "Steemian",
          "slug": "steemian"
        },
        {
          "level": 2,
          "title": "Culture",
          "slug": "culture"
        },
        {
          "level": 3,
          "title": "Downvoting",
          "slug": "downvoting"
        },
        {
          "level": 3,
          "title": "Reward pool rape",
          "slug": "reward-pool-rape"
        },
        {
          "level": 3,
          "title": "#introduceyourself",
          "slug": "introduceyourself"
        },
        {
          "level": 3,
          "title": "Bid bot",
          "slug": "bid-bot"
        },
        {
          "level": 3,
          "title": "Resteem",
          "slug": "resteem"
        },
        {
          "level": 3,
          "title": "Downvote",
          "slug": "downvote"
        },
        {
          "level": 3,
          "title": "Blacklist",
          "slug": "blacklist"
        },
        {
          "level": 3,
          "title": "Curation",
          "slug": "curation"
        },
        {
          "level": 2,
          "title": "Finance",
          "slug": "finance"
        },
        {
          "level": 3,
          "title": "SPS",
          "slug": "sps"
        },
        {
          "level": 3,
          "title": "Steem",
          "slug": "steem"
        },
        {
          "level": 3,
          "title": "Steem Power",
          "slug": "steem-power"
        },
        {
          "level": 3,
          "title": "Steem Dollar",
          "slug": "steem-dollar"
        },
        {
          "level": 3,
          "title": "Delegate",
          "slug": "delegate"
        },
        {
          "level": 2,
          "title": "Tools and utilities",
          "slug": "tools-and-utilities"
        },
        {
          "level": 3,
          "title": "RPC",
          "slug": "rpc"
        },
        {
          "level": 3,
          "title": "Steem Connect",
          "slug": "steem-connect"
        },
        {
          "level": 3,
          "title": "Key chain",
          "slug": "key-chain"
        }
      ],
      "lastUpdated": "12/23/2019, 3:10:21 PM"
    },
    {
      "title": "SDK Guide",
      "frontmatter": {
        "title": "SDK Guide",
        "meta": [
          {
            "name": "description",
            "content": "Glossary of popular Steem and Steemian jargons, terms slangs like 'minor', 'witness' and '#rewardpoolrape'. Find the definition of 'official' terms too, such as 'Steem Dollars', 'Steem Power' and more."
          },
          {
            "name": "keywords",
            "content": "steem glossary, steem jargons, steem terms definition, steem dictionary"
          }
        ]
      },
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-72747704",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "Introduction",
          "slug": "introduction"
        },
        {
          "level": 3,
          "title": "Disclosure",
          "slug": "disclosure"
        },
        {
          "level": 3,
          "title": "Community",
          "slug": "community"
        },
        {
          "level": 3,
          "title": "Business solutions",
          "slug": "business-solutions"
        }
      ],
      "lastUpdated": "12/23/2019, 3:10:21 PM"
    },
    {
      "title": "Privacy policy and Terms of Use",
      "frontmatter": {
        "title": "Privacy policy and Terms of Use",
        "meta": [
          {
            "name": "description",
            "content": "Glossary of popular Steem and Steemian jargons, terms slangs like 'minor', 'witness' and '#rewardpoolrape'. Find the definition of 'official' terms too, such as 'Steem Dollars', 'Steem Power' and more."
          },
          {
            "name": "keywords",
            "content": "steem glossary, steem jargons, steem terms definition, steem dictionary"
          }
        ]
      },
      "regularPath": "/legal/",
      "relativePath": "legal/README.md",
      "key": "v-78e1f0ca",
      "path": "/legal/",
      "headers": [
        {
          "level": 2,
          "title": "Legal",
          "slug": "legal"
        },
        {
          "level": 3,
          "title": "Privacy Policy",
          "slug": "privacy-policy"
        },
        {
          "level": 2,
          "title": "Terms of Use",
          "slug": "terms-of-use"
        },
        {
          "level": 3,
          "title": "1 Terms",
          "slug": "_1-terms"
        },
        {
          "level": 3,
          "title": "2 Use License",
          "slug": "_2-use-license"
        },
        {
          "level": 3,
          "title": "3 Disclaimer",
          "slug": "_3-disclaimer"
        },
        {
          "level": 3,
          "title": "4 Limitations",
          "slug": "_4-limitations"
        },
        {
          "level": 3,
          "title": "5 Accuracy of materials",
          "slug": "_5-accuracy-of-materials"
        },
        {
          "level": 3,
          "title": "6 Links",
          "slug": "_6-links"
        },
        {
          "level": 3,
          "title": "7 Modifications",
          "slug": "_7-modifications"
        },
        {
          "level": 3,
          "title": "8 Governing Law",
          "slug": "_8-governing-law"
        }
      ]
    },
    {
      "title": "Steem JS libraries",
      "frontmatter": {
        "title": "Steem JS libraries",
        "meta": [
          {
            "name": "description",
            "content": "Javascript Steem libraries for building a Steem client, dapp or platform."
          },
          {
            "name": "keywords",
            "content": "steem js, steem javascript, steem libraries"
          }
        ]
      },
      "regularPath": "/libraries/js/",
      "relativePath": "libraries/js/README.md",
      "key": "v-f678053e",
      "path": "/libraries/js/",
      "headers": [
        {
          "level": 2,
          "title": "Utilities",
          "slug": "utilities"
        },
        {
          "level": 3,
          "title": "Steem Utils",
          "slug": "steem-utils"
        }
      ],
      "lastUpdated": "12/23/2019, 3:10:21 PM"
    },
    {
      "title": "Developer resources",
      "frontmatter": {
        "title": "Developer resources",
        "meta": [
          {
            "name": "description",
            "content": "Resources for Steem developers, code specifications, testing endpoint and setup, public RPC API endpoints and more."
          },
          {
            "name": "keywords",
            "content": "steem dev, steem developers, steem devop"
          }
        ]
      },
      "regularPath": "/resources/dev/",
      "relativePath": "resources/dev/README.md",
      "key": "v-2827ac13",
      "path": "/resources/dev/",
      "headers": [
        {
          "level": 2,
          "title": "API",
          "slug": "api"
        },
        {
          "level": 3,
          "title": "Definitions",
          "slug": "definitions"
        },
        {
          "level": 3,
          "title": "Tutorials",
          "slug": "tutorials"
        },
        {
          "level": 3,
          "title": "Services",
          "slug": "services"
        },
        {
          "level": 3,
          "title": "Test net",
          "slug": "test-net"
        }
      ],
      "lastUpdated": "12/23/2019, 3:10:21 PM"
    },
    {
      "title": "Content style guide",
      "frontmatter": {
        "title": "Content style guide",
        "meta": [
          {
            "name": "description",
            "content": "Recommended Steem writing style for content creators on areas ranging from formatting, quality and DCMA."
          },
          {
            "name": "keywords",
            "content": "steem content guide, steem author's guide, recommended Steem writing style"
          }
        ]
      },
      "regularPath": "/standards/content/",
      "relativePath": "standards/content/README.md",
      "key": "v-66b33129",
      "path": "/standards/content/",
      "headers": [
        {
          "level": 2,
          "title": "Formatting",
          "slug": "formatting"
        },
        {
          "level": 3,
          "title": "Use summary as first paragraph",
          "slug": "use-summary-as-first-paragraph"
        },
        {
          "level": 3,
          "title": "Write in markdown whenever possible",
          "slug": "write-in-markdown-whenever-possible"
        },
        {
          "level": 3,
          "title": "Use external image hosts",
          "slug": "use-external-image-hosts"
        },
        {
          "level": 2,
          "title": "Quality",
          "slug": "quality"
        },
        {
          "level": 3,
          "title": "Images",
          "slug": "images"
        },
        {
          "level": 3,
          "title": "Proof-reading",
          "slug": "proof-reading"
        },
        {
          "level": 3,
          "title": "Linking",
          "slug": "linking"
        },
        {
          "level": 2,
          "title": "DCMA",
          "slug": "dcma"
        }
      ],
      "lastUpdated": "12/23/2019, 3:10:21 PM"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/hero.png",
        "heroText": "Hero Title",
        "tagline": "Hero subtitle",
        "actionText": "Get Started →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Simplicity First",
            "details": "Minimal setup with markdown-centered project structure helps you focus on writing."
          },
          {
            "title": "Vue-Powered",
            "details": "Enjoy the dev experience of Vue + webpack, use Vue components in markdown, and develop custom themes with Vue."
          },
          {
            "title": "Performant",
            "details": "VuePress generates pre-rendered static HTML for each page, and runs as an SPA once a page is loaded."
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/standards/culture/",
      "relativePath": "standards/culture/README.md",
      "key": "v-5c143d7f",
      "path": "/standards/culture/",
      "headers": [
        {
          "level": 2,
          "title": "Downvoting",
          "slug": "downvoting"
        }
      ],
      "lastUpdated": "12/23/2019, 3:10:21 PM"
    }
  ],
  "themeConfig": {
    "repo": "steem-sdk/sdk",
    "repoLabel": "Contribute!",
    "docsBranch": "master",
    "editLinks": true,
    "editLinkText": "Help us improve this page!",
    "nav": [
      {
        "text": "Guide",
        "link": "/guide/"
      },
      {
        "text": "Standards",
        "items": [
          {
            "text": "Content",
            "items": [
              {
                "text": "Formatting",
                "link": "/standards/content/#formatting"
              },
              {
                "text": "Quality",
                "link": "/standards/content/#quality"
              },
              {
                "text": "DCMA",
                "link": "/standards/content/#dcma"
              }
            ]
          }
        ]
      },
      {
        "text": "Libraries",
        "items": [
          {
            "text": "Javascript",
            "link": "/libraries/js/"
          }
        ]
      },
      {
        "text": "Resources",
        "items": [
          {
            "text": "Developers",
            "items": [
              {
                "text": "API Specifications",
                "link": "/resources/dev/#api"
              }
            ]
          }
        ]
      },
      {
        "text": "Business solutions",
        "link": "https://steemstudios.com/start"
      },
      {
        "text": "More",
        "items": [
          {
            "text": "Legal",
            "items": [
              {
                "text": "Privacy",
                "link": "/legal/#privacy-policy"
              },
              {
                "text": "Terms",
                "link": "/legal/#terms-of-use"
              }
            ]
          },
          {
            "text": "Links",
            "items": [
              {
                "text": "Slack",
                "link": "https://steemstudios.com/slack"
              },
              {
                "text": "Github",
                "link": "https://github.com/steem-sdk"
              },
              {
                "text": "Steem Institute",
                "link": "https://steem.institute"
              },
              {
                "text": "Steem Studios",
                "link": "https://steeminc.com"
              },
              {
                "text": "Community",
                "link": "https://steemian.net"
              }
            ]
          }
        ]
      }
    ],
    "sidebar": "auto",
    "lastUpdated": "Last Updated",
    "smoothScroll": true
  }
}